### ISSUE TITLE
求数据 

### ISSUE THREAD

**Issue by WuLoMIn** [RunyuFan/UisNet-TGRS-2022#1]
您好 Fine-Scale Urban Informal Settlements Mapping by Fusing Remote Sensing Images and Building Data via a Transformer- Based Multimodal Fusion Network 这篇的论文数据可以再重新分享一下嘛 百度网盘链接失效了

**Comment by RunyuFan** [comment]
(New link)
链接：https://pan.baidu.com/s/1tky1MzlprsMBf49bFc24bg?pwd=268p 
提取码：268p 
--来自百度网盘超级会员V3的分享

**Comment by RunyuFan** [comment]
(New link)
链接：https://pan.baidu.com/s/1tky1MzlprsMBf49bFc24bg?pwd=268p 
提取码：268p 
--来自百度网盘超级会员V3的分享

**Comment by WuLoMIn** [comment]
非常感谢您的分享



---原始邮件---
发件人: "RunyuFan ***@***.***&gt;
发送时间: 2023年8月20日(周日) 上午10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RunyuFan/UisNet-TGRS-2022] 求数据  (Issue #1)




 
(New link)
 链接：https://pan.baidu.com/s/1tky1MzlprsMBf49bFc24bg?pwd=268p
 提取码：268p
 --来自百度网盘超级会员V3的分享

**Comment by Devin-Egber** [comment]
你好,数据集可以麻烦您重新发一下嘛，网盘链接失效了

**Comment by RunyuFan** [comment]
【超级会员V4】通过百度网盘分享的文件：樊润宇-深圳市非…
链接:https://pan.baidu.com/s/12safMvDcUs34TQL15eYQWw?pwd=7448 
提取码:7448
复制这段内容打开「百度网盘APP 即可获取」
