### ISSUE TITLE
求数据

### ISSUE THREAD

**Issue by Devin-Egber** [RunyuFan/UisNet-TGRS-2022#2]
你好，这篇文章“Fine-scale Urban Informal Settlements Mapping by Fusing Remote Sensing Images and Building Data via a Transformer-based Multimodal Fusion Network”的数据集可以重新分享一下吗，您提供的两个百度网盘链接都过期了，谢谢！

**Comment by RunyuFan** [comment]
你好，更新之后的链接如下：
【超级会员V4】通过百度网盘分享的文件：樊润宇-深圳市非…
链接:https://pan.baidu.com/s/12safMvDcUs34TQL15eYQWw?pwd=7448 
提取码:7448
复制这段内容打开「百度网盘APP 即可获取」


---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2024年03月26日 19:50 收件人  ***@***.***> 抄送至  ***@***.***> 主题  [RunyuFan/UisNet-TGRS-2022] 求数据 (Issue #2)  

你好，这篇文章“Fine-scale Urban Informal Settlements Mapping by Fusing Remote Sensing Images and Building Data via a Transformer-based Multimodal Fusion Network”的数据集可以重新分享一下吗，您提供的两个百度网盘链接都过期了，谢谢！
