### ISSUE TITLE
你好，能否再次分享数据集

### ISSUE THREAD

**Issue by kshanzz** [RunyuFan/UisNet-TGRS-2022#4]
之前的百度网盘也都过期了，能否再次分享数据集呢？非常感谢！

**Comment by RunyuFan** [comment]
> 之前的百度网盘也都过期了，能否再次分享数据集呢？非常感谢！

通过百度网盘分享的文件：樊润宇-深圳市非正规居住区语义分割数据集（UIS-Shenzhen）.zip
链接：https://pan.baidu.com/s/1-TnXRGiKz7_OOsnPTvbeKg?pwd=30a9 
提取码：30a9 
--来自百度网盘超级会员V4的分享
